spring:
  artemis:
    user: 'artemis'
    password: 'simetraehcapa'
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${JMS__EXAMPLE__SPRING__MAIL__USERNAME:test}
    password: ${JMS__EXAMPLE__SPRING__MAIL__PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'


gb.api:
  endpoint:
    base-uri: 'stub'
    manufacturer-url: 'http://${gb.api.endpoint.base-uri}/internal/api/v1/manufacturer'
    category-url: 'http://${gb.api.endpoint.base-uri}/internal/api/v1/category'
    product-url: 'http://${gb.api.endpoint.base-uri}/internal/api/v1/product'
    order-url: 'http://${gb.api.endpoint.base-uri}/internal/api/v1/order'
  connection:
    period: 3000 #Mills
    max-period: 5000 #Mills
    max-attempts: 3
    connect-timeout-millis: 10000
    read-timeout-millis: 30000




server:
  port: 8088
